<template>
  <article class="offer-paper" :class="{ 'offer-paper-empty': !hasContent, 'offer-paper-updating': pending }" aria-label="Szkic oferty" :aria-busy="pending">
    <div class="offer-paper-top"><span class="offer-paper-brand"><span aria-hidden="true">o</span> OFERTA USŁUGI</span><span class="offer-paper-status">{{ version ? `SZKIC ${String(version).padStart(2, '0')}` : 'TWÓJ SZKIC' }}</span></div>
    <template v-if="hasContent && draft">
      <div class="offer-paper-intro"><p class="offer-paper-company">{{ draft.company || 'Nazwa firmy do uzupełnienia' }}</p><h3>{{ draft.title || draft.service || 'Twoja oferta' }}</h3><p v-if="draft.location" class="offer-paper-location"><svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M15 8c0 4-5 8-5 8S5 12 5 8a5 5 0 1 1 10 0Z"/><circle cx="10" cy="8" r="1.6"/></svg>{{ draft.location }}</p><p v-else class="offer-paper-missing">Obszar działania do ustalenia</p></div>
      <p v-if="draft.description" class="offer-paper-description">{{ draft.description }}</p>
      <p v-else class="offer-paper-missing">Opis usługi uzupełnimy w rozmowie.</p>
      <section class="offer-paper-section"><h4><span>01</span> Co obejmuje oferta</h4><ul v-if="draft.scope.length" class="offer-paper-scope"><li v-for="(item, index) in draft.scope" :key="index"><span aria-hidden="true">✓</span>{{ item }}</li></ul><p v-else class="offer-paper-missing">Opowiedz, jakie prace wykonujesz.</p></section>
      <div class="offer-paper-facts"><section><span>CENA</span><p :class="{ 'is-missing': !draft.price }">{{ draft.price || 'Do ustalenia' }}</p></section><section><span>TERMIN</span><p :class="{ 'is-missing': !draft.timing }">{{ draft.timing || 'Do ustalenia' }}</p></section></div>
      <section class="offer-paper-section offer-paper-conditions"><h4><span>02</span> Warto wiedzieć</h4><ul v-if="draft.conditions.length"><li v-for="(condition, index) in draft.conditions" :key="index">{{ condition }}</li></ul><p v-else class="offer-paper-missing">Dodatkowe warunki do ustalenia.</p></section>
      <div v-if="draft.nextStep" class="offer-paper-next"><span aria-hidden="true">↗</span><div><strong>Porozmawiajmy o Twoim pomyśle</strong><p>{{ draft.nextStep }}</p></div></div>
    </template>
    <template v-else>
      <div class="offer-paper-empty-intro"><span class="offer-paper-empty-mark" aria-hidden="true"><svg viewBox="0 0 44 44" fill="none"><path d="M26 6H10v32h24V14l-8-8Zm0 0v8h8M16 21h12m-12 6h8" /><path d="m30 30 7-7 3 3-7 7-4 1 1-4Z" /></svg></span><p>MIEJSCE NA TWOJĄ OFERTĘ</p><h3>Każda dobra oferta<br>zaczyna się od rozmowy.</h3><span>Dodaj pierwszy szczegół.<br>Resztę ułożymy krok po kroku.</span></div>
      <div class="offer-paper-outline"><div><span>01</span><div><strong>Twoja usługa</strong><p>Co robisz i komu pomagasz</p></div><span aria-hidden="true">—</span></div><div><span>02</span><div><strong>Zakres i warunki</strong><p>Co zawiera cena i na czym polega współpraca</p></div><span aria-hidden="true">—</span></div><div><span>03</span><div><strong>Cena i termin</strong><p>Konkrety, które pomagają podjąć decyzję</p></div><span aria-hidden="true">—</span></div></div>
    </template>
    <footer class="offer-paper-footer"><span>{{ hasContent ? ready ? 'Przygotowano wspólnie z asystentem' : 'Uzupełnimy brakujące informacje w rozmowie' : 'Twoje słowa. Uporządkowane w ofertę.' }}</span><span aria-hidden="true">✳</span></footer>
  </article>
</template>

<script setup lang="ts">
import type { OfferDraft } from '~~/shared/types/oferteo-creator'
const props = defineProps<{ draft: OfferDraft | null; ready: boolean; version: number; pending: boolean }>()
const hasContent = computed(() => !!props.draft && !!(props.draft.title || props.draft.company || props.draft.service || props.draft.description || props.draft.scope.length || props.draft.location || props.draft.price || props.draft.timing || props.draft.conditions.length || props.draft.nextStep))
</script>

<style scoped>
.offer-paper { width: 100%; max-width: 640px; margin-inline: auto; padding: 30px 40px 20px; border: 1px solid #e7e3dc; border-top: 3px solid #e99040; border-radius: 3px 3px 8px 8px; background: #fff; box-shadow: 0 3px 5px #2d2b2403, 0 14px 34px #2d2b2406; color: #213b58; overflow-wrap: anywhere; }
.offer-paper * { box-sizing: border-box; }.offer-paper p, .offer-paper h3, .offer-paper h4 { margin: 0; }.offer-paper svg { width: 18px; height: 18px; stroke: currentColor; stroke-width: 1.4; stroke-linecap: round; stroke-linejoin: round; }
.offer-paper-top { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding-bottom: 22px; border-bottom: 1px solid #eaece9; }
.offer-paper-brand { display: flex; align-items: center; gap: 8px; color: #728070; font-size: 8px; letter-spacing: 1.3px; font-weight: 500; }.offer-paper-brand>span { color: #df8a39; font-size: 25px; line-height: 1; letter-spacing: -1px; font-weight: 500; }
.offer-paper-status { padding: 4px 7px; border: 1px solid #e9e8e1; border-radius: 4px; color: #7b8172; font-size: 8px; letter-spacing: .8px; white-space: nowrap; }
.offer-paper-intro { padding-top: 29px; }.offer-paper-company { color: #65715f; font-size: 11px; font-weight: 500; }.offer-paper h3 { margin-top: 11px; color: #183958; font-size: clamp(23px,2.1vw,31px); font-weight: 500; line-height: 1.3; letter-spacing: -1px; text-wrap: balance; }
.offer-paper-location { display: flex; align-items: center; gap: 5px; margin-top: 14px!important; color: #6d7c6f; font-size: 11px; }.offer-paper-location svg { width: 15px; height: 15px; }
.offer-paper-description { margin-top: 24px!important; color: #526271; font-size: 12px; line-height: 1.9; white-space: pre-wrap; }.offer-paper-missing { margin-top: 12px!important; color: #788273; font-size: 11px; line-height: 1.8; font-style: italic; }
.offer-paper-section { margin-top: 29px; }.offer-paper h4 { display: flex; align-items: center; gap: 10px; color: #385169; font-size: 12px; font-weight: 500; }.offer-paper h4>span { color: #bb8755; font-size: 9px; font-variant-numeric: tabular-nums; }
.offer-paper-scope { display: grid; gap: 10px; margin: 16px 0 0; padding: 0; list-style: none; }.offer-paper-scope li { display: flex; align-items: baseline; gap: 10px; color: #536474; font-size: 12px; line-height: 1.7; }.offer-paper-scope li>span { color: #6e886f; font-size: 11px; }
.offer-paper-facts { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-top: 27px; padding: 21px 19px; border: 1px solid #ecebe4; border-radius: 6px; background: #fafaf6; }.offer-paper-facts section+section { padding-left: 21px; border-left: 1px solid #e6e8de; }.offer-paper-facts section>span { color: #6e7c68; font-size: 8px; font-weight: 500; letter-spacing: 1.2px; }.offer-paper-facts p { margin-top: 8px; color: #284660; font-size: 14px; font-weight: 500; line-height: 1.6; letter-spacing: -.3px; }.offer-paper-facts .is-missing { color: #788273; font-size: 12px; font-weight: 400; }
.offer-paper-conditions ul { display: grid; gap: 7px; margin: 14px 0 0; padding-left: 14px; color: #67717b; font-size: 11px; line-height: 1.85; }.offer-paper-conditions li { padding-left: 2px; }
.offer-paper-next { display: flex; gap: 10px; margin-top: 25px; padding-top: 23px; border-top: 1px solid #ecece7; }.offer-paper-next>span { font-size: 22px; line-height: 1; color: #c67b34; }.offer-paper-next strong { color: #3e586e; font-size: 12px; font-weight: 500; }.offer-paper-next p { margin-top: 7px; color: #6b7881; font-size: 11px; line-height: 1.8; }
.offer-paper-footer { display: flex; align-items: center; justify-content: space-between; gap: 10px; margin-top: 30px; padding-top: 16px; border-top: 1px solid #ecece7; color: #7e897b; font-size: 8px; line-height: 1.6; }.offer-paper-footer>span:last-child { color: #d99755; font-size: 19px; line-height: 1; }
.offer-paper-empty-intro { padding: 31px 0 29px; text-align: center; }.offer-paper-empty-mark { display: grid; place-items: center; width: 61px; height: 65px; margin: 0 auto 20px; border: 1px solid #eadfce; border-radius: 16px; background: #fffcf6; color: #c98d4a; transform: rotate(-4deg); }.offer-paper-empty-mark svg { width: 38px; height: 38px; stroke-width: 1.2; }.offer-paper-empty-intro>p { color: #8a8877; font-size: 8px; letter-spacing: 1.3px; }.offer-paper-empty-intro h3 { margin-top: 13px; font-size: clamp(23px,2.1vw,29px); line-height: 1.4; }.offer-paper-empty-intro>span:last-child { display: block; margin-top: 13px; color: #7c857a; font-size: 11px; line-height: 1.9; }
.offer-paper-outline { margin-top: 4px; }.offer-paper-outline>div { display: flex; align-items: center; gap: 13px; padding: 16px 0; border-top: 1px solid #edeee8; }.offer-paper-outline>div>span:first-child { color: #bd9876; font-size: 10px; }.offer-paper-outline>div>span:last-child { margin-left: auto; color: #c0c5b9; }.offer-paper-outline strong { color: #617467; font-size: 11px; font-weight: 500; }.offer-paper-outline p { margin-top: 4px; color: #869080; font-size: 9px; line-height: 1.5; }.offer-paper-empty .offer-paper-footer { margin-top: 7px; }
@media (max-width: 1100px) and (min-width: 761px) { .offer-paper { padding: 24px 26px 18px; }.offer-paper-facts { gap: 16px; padding: 17px 14px; }.offer-paper-facts section+section { padding-left: 14px; }.offer-paper-empty-intro { padding-block: 26px; } }
@media (max-width: 500px) { .offer-paper { padding: 24px 24px 18px; }.offer-paper h3 { font-size: 25px; }.offer-paper-facts { gap: 14px; padding: 17px 14px; }.offer-paper-facts section+section { padding-left: 14px; }.offer-paper-facts p { font-size: 13px; }.offer-paper-empty-intro { padding-top: 27px; }.offer-paper-brand { letter-spacing: .8px; }.offer-paper-outline p { font-size: 10px; } }
@media (max-width: 360px) { .offer-paper { padding-inline: 18px; }.offer-paper-facts { grid-template-columns: 1fr; gap: 17px; }.offer-paper-facts section+section { padding: 15px 0 0; border-left: 0; border-top: 1px solid #e6e8de; } }
</style>
